use_frameworks!

'echo "2.0" > .swift-version'

target 'PickyPodWeds_Example' do
  pod 'PickyPodWeds', :path => '../'

  target 'PickyPodWeds_Tests' do
    pod 'PickyPodWeds', :path => '../'
  end
end
